### ISSUE TITLE
Walking trips can't be looked up in the DB

### ISSUE THREAD

**Issue by Nate-Wessel** [Nate-Wessel/routing#10]
See `12 -> 281`
````
Traceback (most recent call last):
  File "access.py", line 21, in <module>
    access(12)
  File "access.py", line 16, in access
    print( len(od.access()),'trips' )
  File "/home/nate/routing/OD.py", line 150, in access
    trips = db.all_itinerary_trips(self.retro_itin(0))
  File "/home/nate/routing/db.py", line 107, in all_itinerary_trips
    'final_depth':len(itin.segments)
psycopg2.ProgrammingError: cannot subscript type unknown because it is not an array
````

**Comment by Nate-Wessel** [comment]
DB should now return an empty list of trips when presented with this issue, which may still not be ideal.

**Comment by Nate-Wessel** [comment]
I think the rest of the solution is just to not try to look these up in the DB
